### ISSUE TITLE
can I deploy it on CF and use it as a pgAdmin?

### ISSUE THREAD

**Issue by wl1711** [cloudfoundry-samples/cf-ex-phppgadmin#1]
Hello,

I wonder if  I set up the environment variable correctly, can I create tables and query using it as pgAdmin?

I can make it run in CF, but there is no way I can create anything in this postgres db, unless I did something wrong?

Thanks,

**Comment by dmikusa** [comment]
Sorry, I'm not sure I understand the issue you're reporting.  Can you elaborate more?

For what it's worth, I can confirm that when deployed PHPPgAdmin should have all the access that is allowed by the user that you used to login to PHPPgAdmin.  In other words, if you log in with a user that has full access to the DB then you'll have full access through the UI.  If you log in with a user that only had read access, then you'll only have read access.  I don't believe the UI changes based on your permissions, I think you'll just get errors when you try to perform an action for which you do not have the right permissions.

Hope that helps!

**Comment by wl1711** [comment]
Sorry, here is my situation.

I set up a postgresql instance in CF. Is there a way to connect to it and create/query the data, like what we can do on our local postgres instance? Can PHPPgAdmin provide that functionality?

I was able to deploy it on CF following the instruction, and updated conifg.inc.php. Once I launch it, I can see the welcome page(language/theme options and a couple of links). On the left panel, Servers was there, but 'No object found'. How to create an server instance? Maybe the config.inc.php was not configured  correctly? 

I created the service using the following:
cf create-service postgresql-9.5-odb small pgsql

In the config.inc.php, I updated
from
        // looks for 'elephantsql' service
        if ($service_provider === 'elephantsql') {
to 
        if ($service_provider === 'postgresql-9.5-odb') {

hope I made myself clear.

**Comment by dmikusa** [comment]
>On the left panel, Servers was there, but 'No object found'. How to create an server instance? Maybe the config.inc.php was not configured correctly?

It sounds like `config.inc.php` is not right.  The question is which part, cause there's two phases to it.

It first attempts to auto-detect services based on what you bind to the app.  The logic is not perfect though and may not catch all services, depending on what metadata the service provider includes.  The code in the same will attempt to first grab any services that are from `elephantsql` (this is what I tested with on PWS).  It then tries to look for more generic clues and searches for services that have a tag of `postgresql` or services where the name contains `pgsql`.

You gave your service the name `pgsql` which meets the third criteria I mentioned so the code should be able to find this.

The second phase after it detects the services is to attempt to parse the config data it needs to connect to Postgres.  You can see that [here](https://github.com/cloudfoundry-samples/cf-ex-phppgadmin/blob/master/htdocs/conf/config.inc.php#L40-L53).  This code is assuming that the credentials presented by the bound service will have a `uri` property from which it can parse the host, port and db name.  I'm not familiar with the service broker you're using so it's possible that it's presenting this information in a slightly different way.  Maybe it has a `url` property or maybe it presents the host, port and db as individual properties.  We just need to find out how it presents the info and adjust the code to pull the information.

Can you run `cf env <your-app-name>`, mask out the sensitive info like passwords & public IPs and post the VCAP_SERVICES output here?  That should help to see what information the bound service is providing to the app.

Thanks!

**Comment by wl1711** [comment]
Below is the output of cf env test123:

System-Provided:
{
 "VCAP_SERVICES": {
  "crunchy-postgresql-9.5-on-demand": [
   {
    "credentials": {
     **"db_host": "xx.xx.xx.xx",
     "db_name": "test",
     "db_port": 5432,**
     "jdbc_read_uri": "jdbc:postgresql://xx.xx.xx.xx:5433/test",
     "jdbc_uri": "jdbc:postgresql://xx.xx.xx.xx:5432/test",
     "password": "vbsakKzr9$RmtBm_JJ!xl9jxx",
     "read_host": "xx.xx.xx.xx",
     "read_port": 5433,
     "read_uri": "postgresql://test8ecdc1c3edd0e8e5fcac0aee1347672c:akKzr9%24RmtBm_JJ%21xl9j@xx.xx.xx.xx:5433/test
     "service_id": "service-instance_572255ff-5c6b-4969-9cbd-9b41fd472a2c",
     **"uri": "postgresql://test8ecdc1c3edd0e8e5fcac0aee1347672c:akKzr9%24RmtBm_JJ%21xl9j@xx.xx.xx.xx:5432/test**
     "username": "ddtest8ecdc1c3edd0e8e5fcac0aee1347672cxx123"
    },
    "label": "crunchy-postgresql-9.5-on-demand",
    "name": "pgsql",
    "plan": "small",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "crunchy",
     "postgresql",
     "postgresql-9.5",
     "on-demand"
    ],
    "volume_mounts": []
   }
  ]
 }
}

{
 "VCAP_APPLICATION": {
  "application_id": "12904537-1bd5-47f2-a8b7-b51100f9e116",
  "application_name": "test123",
  "application_uris": [
   "test123.dev.east.paas.xxxxxxxx.xx"
  ],
  "application_version": "6e4fa2d0-b86a-4c45-bbb3-5bddf7db6e97",
  "cf_api": "https://api.system.dev.east.paas.xxxxxxxx.xx",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 1024
  },
  "name": "test123",
  "space_id": "4d3bc72b-84b3-4cda-895d-2bca1b433559",
  "space_name": "xxxxxxxxxx",
  "uris": [
   "test123.dev.east.paas.xxxxxxxx.xx"
  ],
  "users": null,
  "version": "6e4fa2d0-b86a-4c45-bbb3-5bddf7db6e97"
 }
}

No user-defined env variables have been set

No running env variables have been set

No staging env variables have been set

**Comment by wl1711** [comment]
Output of cf service pgsql:

Service instance: pgsql
Service: crunchy-postgresql-9.5-on-demand
Bound apps: pg1,test123
Tags:
Plan: small

I am not sure why I was using 'postgresql-9.5-odb' and I tried the following, it doesn't make any difference though.
        if ($service_provider === 'crunchy-postgresql-9.5-on-demand') {

**Comment by dmikusa** [comment]
Thanks for posting that.  You shouldn't need to change this part.

>if ($service_provider === 'crunchy-postgresql-9.5-on-demand') {

Your service provider tags the service as `postgresql` which will cause the code to locate the bound service.  You're also using the name `pgsql` which will cause the code to locate your bound service.  Either one is sufficient.

It looks like the code was able to locate the bound service but not parse the `uri` property.  I made a change to the regular expression it's using the parse the information (was previously looking for a url tha starts with `postgres` but your starts with `postgresql`).  Try updating your regular expression and see if it works.

https://github.com/cloudfoundry-samples/cf-ex-phppgadmin/blob/master/htdocs/conf/config.inc.php#L41-L42

**Comment by wl1711** [comment]
That resolved the issue! Thanks you.

Another question is I have to use the username and password from VCAP_SERVICES. Once login, it looks like I can change the password. Is there a way I can create my own username?

When I set up the service_instance(pgsql), it's required to specify db_username, db_name, owner_email, owner_name. Maybe I can specify username and password here?

I tried to set $conf['extra_login_security'] = false, just to test if I can disable the login validation. It doesn't make a difference.

Is this PHPPgAdmin can do pretty much everything as the pgAdmin on our local machine?

Thanks.

**Comment by dmikusa** [comment]
Excellent! Glad to hear it's working now.

>Another question is I have to use the username and password from VCAP_SERVICES. Once login, it looks like I can change the password. Is there a way I can create my own username?

Probably not, but I can't say for sure.  That would depend on your service provider and what they permit.  You'd need to check with them.

>When I set up the service_instance(pgsql), it's required to specify db_username, db_name, owner_email, owner_name. Maybe I can specify username and password here?
>I tried to set $conf['extra_login_security'] = false, just to test if I can disable the login validation. It doesn't make a difference.

You might be able to configure PHPPgAdmin to auto-login but you need to be careful if you do that cause then anyone that has access to the URL can access your data.  It's a little redundant to enter the login info into the UI, but it does give you some level of protection.

>Is this PHPPgAdmin can do pretty much everything as the pgAdmin on our local machine?

Yes, it's exactly the same code.  We just overlay a custom configuration so that it picks up the service instance information from VCAP_SERVICES.

Hope that helps!

**Comment by wl1711** [comment]
Thanks, that helps a lot.
